// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  Coordinates of a point on the globe. Mostly used for {@link Cities}.
 */
@javax.xml.bind.annotation.XmlType (
  name = "coords",
  namespace = ""
)
public class Coords implements java.io.Serializable {

  private java.lang.Double _longitude;
  private java.lang.Double _latitude;

  /**
   * The longitude part of the coordinates.
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "long",
    namespace = "",
    required = false
  )
  public java.lang.Double getLongitude() {
    return this._longitude;
  }

  /**
   * The longitude part of the coordinates.
   */
  public void setLongitude(java.lang.Double _longitude) {
    this._longitude = _longitude;
  }

  /**
   * The latitude part of the coordinates.
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "lat",
    namespace = "",
    required = false
  )
  public java.lang.Double getLatitude() {
    return this._latitude;
  }

  /**
   * The latitude part of the coordinates.
   */
  public void setLatitude(java.lang.Double _latitude) {
    this._latitude = _latitude;
  }

}
