// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  This class represents a country on earth.
 */
@javax.xml.bind.annotation.XmlType (
  name = "country",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "country",
  namespace = ""
)
public class Country implements java.io.Serializable {

  private java.lang.String _name;
  private java.lang.String _code;

  /**
   * The country's name. Can be a localized name - e.g.
   * <em>&quot;Austria&quot;</em> or
   * <em>&quot;&Ouml;sterreich&quot;</em> for Austria if the German
   * name was requested.
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "name",
    namespace = "",
    required = false
  )
  public java.lang.String getName() {
    return this._name;
  }

  /**
   * The country's name. Can be a localized name - e.g.
   * <em>&quot;Austria&quot;</em> or
   * <em>&quot;&Ouml;sterreich&quot;</em> for Austria if the German
   * name was requested.
   */
  public void setName(java.lang.String _name) {
    this._name = _name;
  }

  /**
   * The country's <a
   * href="http://www.iso.org/iso/english_country_names_and_code_elements"
   * >ISO code</a>. E.g. <em>&quot;ie&quot;</em> for Ireland
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "code",
    namespace = "",
    required = false
  )
  public java.lang.String getCode() {
    return this._code;
  }

  /**
   * The country's <a
   * href="http://www.iso.org/iso/english_country_names_and_code_elements"
   * >ISO code</a>. E.g. <em>&quot;ie&quot;</em> for Ireland
   */
  public void setCode(java.lang.String _code) {
    this._code = _code;
  }

}
