// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  A {@link Result} consisting of a list of countries.
 */
@javax.xml.bind.annotation.XmlType (
  name = "countries",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "countries",
  namespace = ""
)
public class Countries extends fm.setlist.api.model.Result<fm.setlist.api.model.Country> {

  private java.util.ArrayList<fm.setlist.api.model.Country> _list;

  /**
   * result list of countries
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "country",
    namespace = ""
  )
  public java.util.ArrayList<fm.setlist.api.model.Country> getList() {
    return this._list;
  }

  /**
   * result list of countries
   */
  public void setList(java.util.ArrayList<fm.setlist.api.model.Country> _list) {
    this._list = _list;
  }

}
