// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  A setlist consists of different (at least one) sets. Sets can either be sets
 *  as defined in the <a href="http://www.setlist.fm/guidelines">Guidelines</a>
 *  or encores.
 */
@javax.xml.bind.annotation.XmlType (
  name = "set",
  namespace = ""
)
public class Set implements java.io.Serializable {

  private java.lang.String _name;
  private java.util.ArrayList<fm.setlist.api.model.Song> _songs;

  /**
   * the description/name of the set. E.g.
   * <em>&quot;Acoustic set&quot;</em> or
   * <em>&quot;Paul McCartney solo&quot;</em>
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "name",
    namespace = "",
    required = false
  )
  public java.lang.String getName() {
    return this._name;
  }

  /**
   * the description/name of the set. E.g.
   * <em>&quot;Acoustic set&quot;</em> or
   * <em>&quot;Paul McCartney solo&quot;</em>
   */
  public void setName(java.lang.String _name) {
    this._name = _name;
  }

  /**
   * this set's songs
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "song",
    namespace = "",
    required = true
  )
  public java.util.ArrayList<fm.setlist.api.model.Song> getSongs() {
    return this._songs;
  }

  /**
   * this set's songs
   */
  public void setSongs(java.util.ArrayList<fm.setlist.api.model.Song> _songs) {
    this._songs = _songs;
  }

}
