// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  A {@link Result} consisting of a list of setlists.
 */
@javax.xml.bind.annotation.XmlType (
  name = "setlists",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "setlists",
  namespace = ""
)
public class Setlists extends fm.setlist.api.model.Result<fm.setlist.api.model.Setlist> {

  private java.util.ArrayList<fm.setlist.api.model.Setlist> _list;

  /**
   * result list of setlists
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "setlist",
    namespace = ""
  )
  public java.util.ArrayList<fm.setlist.api.model.Setlist> getList() {
    return this._list;
  }

  /**
   * result list of setlists
   */
  public void setList(java.util.ArrayList<fm.setlist.api.model.Setlist> _list) {
    this._list = _list;
  }

}
