// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  Setlists, that's what it's all about. So if you're trying to use this API
 *  without knowing what a setlist is then you're kinda wrong on this page ;-).
 *  
 *  A setlist can be distinguished from other setlists by its unique id. But as
 *  <a href="http://www.setlist.fm/">setlist.fm</a> works the wiki way, there can
 *  be different versions of one setlist (each time a user updates a setlist a
 *  new version gets created). These different versions have a unique id on its
 *  own. So setlists can have the same id although they differ as far as the
 *  content is concerned - thus the best way to check if two setlists are the
 *  same is to compare their versionIds.
 */
@javax.xml.bind.annotation.XmlType (
  name = "setlist",
  namespace = "",
  propOrder = {"artist", "venue", "sets", "info", "url"}
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "setlist",
  namespace = ""
)
public class Setlist implements java.io.Serializable {

  private java.lang.String _id;
  private java.lang.String _eventDate;
  private java.lang.String _versionId;
  private java.lang.String _tour;
  private java.lang.Integer _lastFmEventId;
  private fm.setlist.api.model.Artist _artist;
  private fm.setlist.api.model.Venue _venue;
  private java.util.ArrayList<fm.setlist.api.model.Set> _sets;
  private java.lang.String _info;
  private java.lang.String _url;

  /**
   * unique identifier
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "id",
    namespace = "",
    required = true
  )
  public java.lang.String getId() {
    return this._id;
  }

  /**
   * unique identifier
   */
  public void setId(java.lang.String _id) {
    this._id = _id;
  }

  /**
   * date of the concert in the format &quot;dd-MM-yyyy&quot;
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "eventDate",
    namespace = "",
    required = true
  )
  public java.lang.String getEventDate() {
    return this._eventDate;
  }

  /**
   * date of the concert in the format &quot;dd-MM-yyyy&quot;
   */
  public void setEventDate(java.lang.String _eventDate) {
    this._eventDate = _eventDate;
  }

  /**
   * unique identifier of the version
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "versionId",
    namespace = "",
    required = true
  )
  public java.lang.String getVersionId() {
    return this._versionId;
  }

  /**
   * unique identifier of the version
   */
  public void setVersionId(java.lang.String _versionId) {
    this._versionId = _versionId;
  }

  /**
   * the setlist's tour
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "tour",
    namespace = "",
    required = false
  )
  public java.lang.String getTour() {
    return this._tour;
  }

  /**
   * the setlist's tour
   */
  public void setTour(java.lang.String _tour) {
    this._tour = _tour;
  }

  /**
   * the id this event has on <a href="http://last.fm/">last.fm</a>
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "lastFmEventId",
    namespace = "",
    required = false
  )
  public java.lang.Integer getLastFmEventId() {
    return this._lastFmEventId;
  }

  /**
   * the id this event has on <a href="http://last.fm/">last.fm</a>
   */
  public void setLastFmEventId(java.lang.Integer _lastFmEventId) {
    this._lastFmEventId = _lastFmEventId;
  }

  /**
   * the setlist's artist
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artist",
    namespace = ""
  )
  public fm.setlist.api.model.Artist getArtist() {
    return this._artist;
  }

  /**
   * the setlist's artist
   */
  public void setArtist(fm.setlist.api.model.Artist _artist) {
    this._artist = _artist;
  }

  /**
   * the setlist's venue
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "venue",
    namespace = ""
  )
  public fm.setlist.api.model.Venue getVenue() {
    return this._venue;
  }

  /**
   * the setlist's venue
   */
  public void setVenue(fm.setlist.api.model.Venue _venue) {
    this._venue = _venue;
  }

  /**
   * all sets of this setlist
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "set",
    namespace = ""
  )
  @javax.xml.bind.annotation.XmlElementWrapper (
    name = "sets",
    namespace = ""
  )
  public java.util.ArrayList<fm.setlist.api.model.Set> getSets() {
    return this._sets;
  }

  /**
   * all sets of this setlist
   */
  public void setSets(java.util.ArrayList<fm.setlist.api.model.Set> _sets) {
    this._sets = _sets;
  }

  /**
   * additional information on the concert - see the <a
   * href="http://www.setlist.fm/guidelines">setlist.fm guidelines</a>
   * for a complete list of allowed content.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "info",
    namespace = ""
  )
  public java.lang.String getInfo() {
    return this._info;
  }

  /**
   * additional information on the concert - see the <a
   * href="http://www.setlist.fm/guidelines">setlist.fm guidelines</a>
   * for a complete list of allowed content.
   */
  public void setInfo(java.lang.String _info) {
    this._info = _info;
  }

  /**
   * the attribution url to which you have to link to wherever you use
   * data from this setlist in your application
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "url",
    namespace = ""
  )
  public java.lang.String getUrl() {
    return this._url;
  }

  /**
   * the attribution url to which you have to link to wherever you use
   * data from this setlist in your application
   */
  public void setUrl(java.lang.String _url) {
    this._url = _url;
  }

}
