// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  This class represents a user.
 */
@javax.xml.bind.annotation.XmlType (
  name = "user",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "user",
  namespace = ""
)
public class User implements java.io.Serializable {

  private java.lang.String _flickr;
  private java.lang.String _twitter;
  private java.lang.String _website;
  private java.lang.String _userId;
  private java.lang.String _lastFm;
  private java.lang.String _mySpace;
  private java.lang.String _fullname;
  private java.lang.String _about;
  private java.lang.String _url;

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "flickr",
    namespace = "",
    required = false
  )
  public java.lang.String getFlickr() {
    return this._flickr;
  }

  /**
   * (no documentation provided)
   */
  public void setFlickr(java.lang.String _flickr) {
    this._flickr = _flickr;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "twitter",
    namespace = "",
    required = false
  )
  public java.lang.String getTwitter() {
    return this._twitter;
  }

  /**
   * (no documentation provided)
   */
  public void setTwitter(java.lang.String _twitter) {
    this._twitter = _twitter;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "website",
    namespace = "",
    required = false
  )
  public java.lang.String getWebsite() {
    return this._website;
  }

  /**
   * (no documentation provided)
   */
  public void setWebsite(java.lang.String _website) {
    this._website = _website;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "userId",
    namespace = "",
    required = false
  )
  public java.lang.String getUserId() {
    return this._userId;
  }

  /**
   * (no documentation provided)
   */
  public void setUserId(java.lang.String _userId) {
    this._userId = _userId;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "lastFm",
    namespace = "",
    required = false
  )
  public java.lang.String getLastFm() {
    return this._lastFm;
  }

  /**
   * (no documentation provided)
   */
  public void setLastFm(java.lang.String _lastFm) {
    this._lastFm = _lastFm;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "mySpace",
    namespace = "",
    required = false
  )
  public java.lang.String getMySpace() {
    return this._mySpace;
  }

  /**
   * (no documentation provided)
   */
  public void setMySpace(java.lang.String _mySpace) {
    this._mySpace = _mySpace;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "fullname",
    namespace = "",
    required = false
  )
  public java.lang.String getFullname() {
    return this._fullname;
  }

  /**
   * (no documentation provided)
   */
  public void setFullname(java.lang.String _fullname) {
    this._fullname = _fullname;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "about",
    namespace = ""
  )
  public java.lang.String getAbout() {
    return this._about;
  }

  /**
   * (no documentation provided)
   */
  public void setAbout(java.lang.String _about) {
    this._about = _about;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "url",
    namespace = ""
  )
  public java.lang.String getUrl() {
    return this._url;
  }

  /**
   * (no documentation provided)
   */
  public void setUrl(java.lang.String _url) {
    this._url = _url;
  }

}
