// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  Venues are places where concerts take place. They usually consist of a venue
 *  name and a city - but there are also some venues that do not have a city
 *  attached yet. In such a case, the city simply isn't set and the city and
 *  country may (but do not have to) be in the name.
 */
@javax.xml.bind.annotation.XmlType (
  name = "venue",
  namespace = "",
  propOrder = {"city", "url"}
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "venue",
  namespace = ""
)
public class Venue implements java.io.Serializable {

  private java.lang.String _id;
  private java.lang.String _name;
  private fm.setlist.api.model.City _city;
  private java.lang.String _url;

  /**
   * unique identifier
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "id",
    namespace = "",
    required = false
  )
  public java.lang.String getId() {
    return this._id;
  }

  /**
   * unique identifier
   */
  public void setId(java.lang.String _id) {
    this._id = _id;
  }

  /**
   * the name of the venue, usually without city and country. E.g.
   * <em>&quot;Madison Square Garden&quot;</em> or
   * <em>&quot;Royal Albert Hall&quot;</em>
   */
  @javax.xml.bind.annotation.XmlAttribute (
    name = "name",
    namespace = "",
    required = false
  )
  public java.lang.String getName() {
    return this._name;
  }

  /**
   * the name of the venue, usually without city and country. E.g.
   * <em>&quot;Madison Square Garden&quot;</em> or
   * <em>&quot;Royal Albert Hall&quot;</em>
   */
  public void setName(java.lang.String _name) {
    this._name = _name;
  }

  /**
   * the city in which the venue is located
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "city",
    namespace = ""
  )
  public fm.setlist.api.model.City getCity() {
    return this._city;
  }

  /**
   * the city in which the venue is located
   */
  public void setCity(fm.setlist.api.model.City _city) {
    this._city = _city;
  }

  /**
   * the attribution url
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "url",
    namespace = ""
  )
  public java.lang.String getUrl() {
    return this._url;
  }

  /**
   * the attribution url
   */
  public void setUrl(java.lang.String _url) {
    this._url = _url;
  }

}
