// Generated by Enunciate
package fm.setlist.api.model;

/**
 *  A {@link Result} consisting of a list of venues.
 */
@javax.xml.bind.annotation.XmlType (
  name = "venues",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "venues",
  namespace = ""
)
public class Venues extends fm.setlist.api.model.Result<fm.setlist.api.model.Venue> {

  private java.util.ArrayList<fm.setlist.api.model.Venue> _list;

  /**
   * result list of venues
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "venue",
    namespace = ""
  )
  public java.util.ArrayList<fm.setlist.api.model.Venue> getList() {
    return this._list;
  }

  /**
   * result list of venues
   */
  public void setList(java.util.ArrayList<fm.setlist.api.model.Venue> _list) {
    this._list = _list;
  }

}
